<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    //
    protected $table = 'subject';
    protected $fillable= ['final','content','fid','parId','score','type','id'];

    public function Answer(){
         return $this->hasMany('App\Answer','subjectId','id');
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        //在题目删除时执行
        self::deleting(function ($subject){
            //删除对应答案
            $subject->Answer()->detach();
        });
    }
}
